## Solving Problem statement 1:
Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.

In [ ]:
# Importing the python array and system library
import numpy as np
import os

def matrix_product(arr_first, arr_second):
    # Compute the matrix product of M x N and A x M using numpy.dot
    result = np.dot(arr_first, arr_second)
    return result


# Get the elements of matrix M x N
def create_array(rows_length,cols_length):
    arr_shape = str(rows_length)+","+ str(cols_length)
    listA = []
    for i in range(rows_length):
          row = list(map(np.float64,input().split()))
          listA.append(row)
    arr_frst = np.array(listA)


   #Check if array size entered equal to M x N
    if arr_frst.ndim  == 2 and arr_frst.shape == (rows_length,cols_length):
      return(arr_frst)
    else:
      return(np.array(["Error occured"]))

#Welcome message
username = ""
try:
  #  Retrieve user name from the local system
  username = os.getlogin()
except:
  username = "user"
print("Hi "+username+", this program multiply a M × N matrix by N × A atrix and create a real matrix product")

# Get the size of matrix M x N and N x A
rows_m, rows_n, col_a = map(int, input("Enter the value of M, N and A (m n a): ").split())
arr_shape = str(rows_m) +","+str(rows_n)

# Enter the first matrix
print("Enter the list elements of  matrix M x N ("+arr_shape+"), and seperate row elements by a space. To enter next row elements, press a key enter :")
first_arr = create_array(rows_m,rows_n)

# Print the first matrix if no error
if first_arr.dtype != float:
  raise Exception("You suppose to enter array with same size you entered previously. i.e Your previouse entered array shape: "+arr_shape)
print("First Array:")
print(first_arr)

# Enter the second matrix
arr_shape = str(rows_n) +","+str(col_a)
print("Enter the list elements of  matrix M x N ("+arr_shape+"), and seperate row elements by a space. To enter next row elements, press a key enter :")
second_arr = create_array(rows_n,col_a)

# Print the second matrix if no error
if second_arr.dtype != float:
  raise Exception("You suppose to enter array with same size you entered previously. i.e Your previouse entered array shape: "+arr_shape)
print("Second Array:")
print(second_arr)

# Print the dot product of the two arrays (First and Second array)
print("Dot product of two arrays:")
arr_product = matrix_product(first_arr,second_arr)
print(arr_product)

Hi user, this program multiply a M × N matrix by N × A atrix and create a real matrix product
Enter the value of M, N and A (m n a): 2 3 4
Enter the list elements of  matrix M x N (2,3) and seperate each element with a space, and press enter key to enter next row elements:
7.984984987 7.989857874 3.74848744
0.7848787843 8.983747847 9.4787487833
First Array:
[[7.98498499 7.98985787 3.74848744]
 [0.78487878 8.98374785 9.47874878]]
Enter the list elements of  matrix M x N (3,4) and seperate each element with a space, and press enter key to enter next row elements:
7.8737878448 9.78476376 9.0903847438 8.8778433674
7.87374674674 8.48947874878372873 6.7878788878 8.8937487374
8.8773474676 7.784783784784 6.74874837847 5.747874878378748
Second Array:
[[7.87378784 9.78476376 9.09038474 8.87784337]
 [7.87374675 8.48947875 6.78787889 8.89374874]
 [8.87734747 7.78478378 6.74874838 5.74787488]]
Dot product of two arrays:
[[159.05882066 175.14208459 152.11837182 163.49507117]
 [161.06187092 157.73719

# Solving Problem statement 2
Write a NumPy program to check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only.
Hint: You can use isdigit(),islower(), and isupper() function.

In [ ]:
# Importing the python array and system library
import numpy as np
import os

# Welcome Message
username = ""
try:
  #  Retrieve user name from the local system
  username = os.getlogin()
except:
  username = "user"
print("Hi "+username+", this program check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only")

# Ënter the array elements
list_a = []
while True: # loop until last array elements
  element = input("Enter an element (-1 to stop, press enter key to continue): ")
  if element == "-1":
    break
  list_a.append(element)

# Convert the list to array
arr = np.array(list_a)

# Print the original array and the resulting boolean results (if each element of the array is composed of digits, lowercase letters, and uppercase letters only)
print('Input: Original array:', arr)

# Determine if the input array is digits only and print the boolean results
is_digits = [arr_element.isdigit() for arr_element in arr]
print("Output: Digits only Boolean results of the above original array strings = ",is_digits)

# Determine if the input array is uppercase only and print the boolean results
pad_left_len = "".ljust(len("output"))
is_uppercase = [arr_element.isupper() for arr_element in arr]
print(pad_left_len+": Upper cases only Boolean results of the above original array strings = ",is_uppercase)

# Determine if the input array is lowercase only and print the boolean results
is_lowercase = [arr_element.islower() for arr_element in arr]
print(pad_left_len+": Lower cases only Boolean results of the above original array strings = ",is_lowercase)

Hi user, this program check if each element of an array of your choice is composed of digits, lower case letters, and upper case letters only
Enter an element (-1 to stop, press enter key to continue): rytwtyrr6676r76
Enter an element (-1 to stop, press enter key to continue): Afgfgdgett566567
Enter an element (-1 to stop, press enter key to continue): -273633773dgtftfdt
Enter an element (-1 to stop, press enter key to continue): Atret5657
Enter an element (-1 to stop, press enter key to continue): adsfrer567
Enter an element (-1 to stop, press enter key to continue): AARRT2
Enter an element (-1 to stop, press enter key to continue): aaddr3
Enter an element (-1 to stop, press enter key to continue): 15623626382
Enter an element (-1 to stop, press enter key to continue): -1
Input: Original array: ['rytwtyrr6676r76' 'Afgfgdgett566567' '-273633773dgtftfdt' 'Atret5657'
 'adsfrer567' 'AARRT2' 'aaddr3' '15623626382']
Output: Digits only Boolean results of the above original array strings =  

# Solve Problem Statement 3
Write a program that reads two space-separated positive integers 𝑋 and
𝑌 as input and perform the following tasks:
Tasks to be performed:
1. Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋
2. Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -
np2)
6. Print all the elements of np3 in a single dimension list like the format as shown below:
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]



In [ ]:
# Importing the python array and system library
import numpy as np
import os

# Welcome Message
username = ""
try:
  #  Retrieve user name from the local system
  username = os.getlogin()
except:
  username = "user"
print("Hi "+username+", this program reads two space-separated positive integers x and y as input and perform few array tasks below")

# Enter two seoerated positive integers
int_x, int_y = map(int,input("Enter two space-separated positive integers  x and y: ").split())

# Create a list (lst1) starting at one (1) with 16 elements at a step of x
lst1 = list(range(1,int_x*16 + 1,int_x))

# Create a list (lst2) starting at one (1) with 16 elements at a step of y
lst2 = list(range(1,int_y*16 + 1,int_y))

# Create NumPy array np1 using lst1
np1_arr = np.array(lst1)

# Create NumPy array np2 using lst2
np2_arr = np.array(lst2)

# Reshape the NumPy array np1_arr to (4,4)
np1_arr_rshape = np1_arr.reshape(4,4)

# Reshape the NumPy array np2_arr to (4,4)
np2_arr_rshape = np2_arr.reshape(4,4)

# Create a new np array (np3) with values obtained by subtracting both the reshaped arrays (np1 -np2)
np3_arr = np1_arr_rshape - np2_arr_rshape

# Print all the elements of np3 in a single dimension
np3_dim = np3_arr.flatten()
print("Output: One dimensional array from n dimension array:\n",np3_dim) # One dimension results from previous two array transformations (2 list with steps -to- 2 array, 2 array -to- 2 reshape array,  2 reshape array -to- difference & difference to 1dim array)")

Hi user, this program reads two space-separated positive integers x and y as input and perform few array tasks
Enter two space-separated positive integers  x and y: 2 3
Output: One dimensional array from n dimension array:
 [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


# Solving Problem Statement 4
Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).

In [ ]:
# Importing the python array and system library
import numpy as np
import os

# Welcome Message
username = ""
try:
  #  Retrieve user name from the local system
  username = os.getlogin()
except:
  username = "user"
print("Hi "+username+", akes two integer-NumPy arrays, P and Q of shape [3∗3] and performthe few tasks below")

# Enter a (3 * 3) integer-NumPy arrays, P
print("Enter a (3 * 3) integer-NumPy arrays 'P' (use space to seperate array elements, enter all elements on one line, and press enter key to save)")
list_p = []
lst = list(map(int, input().split()))
list_p.append(lst) # Create a list
matrx_p = np.array(list_p).reshape(3,3) # create array for a list

# Enter a (3 * 3) integer-NumPy arrays, Q
print("Enter a (3 * 3) integer-NumPy arrays 'Q'(use space to seperate array elements, enter all elements on one line, and press enter key to save)")
list_q = []
lst = list(map(int, input().split()))
list_q.append(lst) # Create a list
matrx_q = np.array(list_q).reshape(3,3) # create array for a list

# Find the element-wise difference of the matrix P (matrix p) and Q (matrix q)
difr_matrx = matrx_p - matrx_q

# Print the element-wise difference of the matrix P (matrix p) and Q (matrix q)
print("Element-wise difference of the matrix P and Q (matrx_p - matrx_q):\n",difr_matrx)

Hi user, akes two integer-NumPy arrays, P and Q of shape [3∗3] and performthe few tasks below
Enter a (3 * 3) integer-NumPy arrays 'P' (use space to seperate array elements, enter all elements on one line, and press enter key to save)
1 2 3 4 5 6 7 8 9
Enter a (3 * 3) integer-NumPy arrays 'Q'(use space to seperate array elements, enter all elements on one line, and press enter key to save)
2 4 6 8 10 12 14 16 18
Element-wise difference of the matrix P and Q (matrx_p - matrx_q):
 [[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
